f = open("akash.txt")
print(f.read())
print('nothin')
f.seek(0)
print(f.read())
print('nothin')
f.seek(0)
print(f.readline())
print(f.readline())
print(f.readline())
print(f.readline())
print(f.readline())
print(f.closed)
f.close()
print(f.closed)